;;; test/benedict-chat-fold-test.el --- Tests for chat folding adapter -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'benedict-chat-fold)

(ert-deftest benedict-chat-fold-thinking-overlay-tracks-append ()
  (with-temp-buffer
    (benedict-chat-fold-init-buffer)
    (let* ((start (point-marker))
           (item (list :content-start start)))
      (insert "thinking")
      (let ((end (copy-marker (point) t)))
        (plist-put item :content-end end)
        (plist-put item :thinking-folded t)
        (benedict-chat-fold-set-thinking-folded item t)
        (let ((fold (plist-get item :thinking-fold)))
          (should (benedict-fold-core-folded-p fold))
          (should (eq (get-char-property (marker-position start) 'invisible)
                      'benedict-chat-thinking)))
        (goto-char (marker-position end))
        (insert " more")
        (benedict-chat-fold-update-thinking item)
        (let ((fold (plist-get item :thinking-fold)))
          (should (benedict-fold-core-folded-p fold))
          (should (eq (get-char-property (1- (point)) 'invisible)
                      'benedict-chat-thinking)))))))

(ert-deftest benedict-chat-fold-filter-buffer-substring-strips-properties ()
  (with-temp-buffer
    (benedict-chat-fold-init-buffer)
    (insert (propertize "hidden" 'invisible 'benedict-chat-thinking))
    (let ((text (filter-buffer-substring (point-min) (point-max))))
      (should (equal text "hidden"))
      (should-not (cl-loop for i below (length text)
                           thereis (get-text-property i 'invisible text))))))

(ert-deftest benedict-chat-fold-isearch-opens-only-current-fold ()
  (with-temp-buffer
    (benedict-chat-fold-init-buffer)
    (should (eq search-invisible t))
    (let* ((think-start (point-marker))
           (thinking (list :content-start think-start))
           think-end)
      (insert "thinking")
      (plist-put thinking :content-end (copy-marker (point)))
      (setq think-end (plist-get thinking :content-end))
      (plist-put thinking :thinking-folded t)
      (benedict-chat-fold-set-thinking-folded thinking t)
      (insert "\n")
      (let* ((tool-start (point-marker))
             (tool (list :content-start tool-start)))
        (insert "tool-body")
        (plist-put tool :content-end (copy-marker (point) t))
        (plist-put tool :tool-folded t)
        (benedict-chat-fold-set-tool-folded tool t)
        (benedict-fold-core-resize (plist-get thinking :thinking-fold)
                                   (marker-position think-start)
                                   (marker-position think-end))
        (cl-labels
            ((state (tag)
                    (message
                     "isearch %s: think char=%S text=%S alias=%S tool char=%S text=%S alias=%S overlays=%S"
                     tag
                     (get-char-property (marker-position think-start) 'invisible)
                     (get-text-property (marker-position think-start) 'invisible)
                     (benedict-chat-fold--isearch-alias-at (marker-position think-start))
                     (get-char-property (marker-position tool-start) 'invisible)
                     (get-text-property (marker-position tool-start) 'invisible)
                     (benedict-chat-fold--isearch-alias-at (marker-position tool-start))
                     (mapcar (lambda (ov)
                               (list (overlay-start ov)
                                     (overlay-end ov)
                                     (overlay-get ov 'invisible)))
                             (overlays-in (point-min) (point-max))))))
          (benedict-chat-fold--isearch-open)
          (state "after-open")
          (let ((isearch-success t)
                (isearch-other-end (marker-position think-start)))
            (benedict-chat-fold--isearch-update))
          (state "after-think-match")
          (should-not (get-char-property (marker-position think-start) 'invisible))
          (should (eq (get-text-property (marker-position tool-start) 'invisible)
                      'benedict-tool-details))
          (let ((isearch-success t)
                (isearch-other-end (marker-position tool-start)))
            (benedict-chat-fold--isearch-update))
          (state "after-tool-match")
          (should (eq (get-char-property (marker-position think-start) 'invisible)
                      'benedict-chat-thinking))
          (should-not (get-text-property (marker-position tool-start) 'invisible))
          (benedict-chat-fold--isearch-close)
          (state "after-close")
          (should (eq (get-char-property (marker-position think-start) 'invisible)
                      'benedict-chat-thinking))
          (should (eq (get-text-property (marker-position tool-start) 'invisible)
                      'benedict-tool-details)))))))

(provide 'test/benedict-chat-fold-test)
;;; test/benedict-chat-fold-test.el ends here
