;;; test/benedict-chat-fold-test.el --- Tests for chat folding adapter -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'benedict-chat)
(require 'benedict-chat-fold)
(require 'benedict-chat-render)

(defmacro benedict-chat-fold-test--with-chat-buffer (&rest body)
  "Evaluate BODY inside a real benedict chat buffer fixture."
  (declare (indent 0) (debug t))
  `(let ((buf (generate-new-buffer " *benedict-chat-fold*")))
     (unwind-protect
         (with-current-buffer buf
           (benedict-chat-mode)
           (benedict-chat--init-buffer)
           ,@body)
       (when (buffer-live-p buf)
         (kill-buffer buf)))))

(ert-deftest benedict-chat-fold-thinking-overlay-tracks-append ()
  (with-temp-buffer
    (benedict-chat-fold-init-buffer)
    (let* ((start (point-marker))
           (item (list :content-start start)))
      (insert "thinking")
      (let ((end (copy-marker (point) t)))
        (plist-put item :content-end end)
        (plist-put item :thinking-folded t)
        (benedict-chat-fold-set-thinking-folded item t)
        (let ((fold (plist-get item :thinking-fold)))
          (should (benedict-fold-core-folded-p fold))
          (should (eq (get-char-property (marker-position start) 'invisible)
                      'benedict-chat-thinking)))
        (goto-char (marker-position end))
        (insert " more")
        (benedict-chat-fold-update-thinking item)
        (let ((fold (plist-get item :thinking-fold)))
          (should (benedict-fold-core-folded-p fold))
          (should (eq (get-char-property (1- (point)) 'invisible)
                      'benedict-chat-thinking)))))))

(ert-deftest benedict-chat-fold-filter-buffer-substring-strips-properties ()
  (with-temp-buffer
    (benedict-chat-fold-init-buffer)
    (insert (propertize "hidden" 'invisible 'benedict-chat-thinking))
    (let ((text (filter-buffer-substring (point-min) (point-max))))
      (should (equal text "hidden"))
      (should-not (cl-loop for i below (length text)
                           thereis (get-text-property i 'invisible text))))))

(ert-deftest benedict-chat-fold-isearch-opens-only-current-fold ()
  (with-temp-buffer
    (benedict-chat-fold-init-buffer)
    (should (eq search-invisible t))
    (let* ((think-start (point-marker))
           (thinking (list :content-start think-start))
           think-end)
      (insert "thinking")
      (plist-put thinking :content-end (copy-marker (point)))
      (setq think-end (plist-get thinking :content-end))
      (plist-put thinking :thinking-folded t)
      (benedict-chat-fold-set-thinking-folded thinking t)
      (insert "\n")
      (let* ((tool-start (point-marker))
             (tool (list :content-start tool-start)))
        (insert "tool-body")
        (plist-put tool :content-end (copy-marker (point) t))
        (plist-put tool :tool-folded t)
        (benedict-chat-fold-set-tool-folded tool t)
        (benedict-fold-core-resize (plist-get thinking :thinking-fold)
                                   (marker-position think-start)
                                   (marker-position think-end))
        (cl-labels
            ((state (tag)
                    (message
                     "isearch %s: think char=%S text=%S alias=%S tool char=%S text=%S alias=%S overlays=%S"
                     tag
                     (get-char-property (marker-position think-start) 'invisible)
                     (get-text-property (marker-position think-start) 'invisible)
                     (benedict-chat-fold--isearch-alias-at (marker-position think-start))
                     (get-char-property (marker-position tool-start) 'invisible)
                     (get-text-property (marker-position tool-start) 'invisible)
                     (benedict-chat-fold--isearch-alias-at (marker-position tool-start))
                     (mapcar (lambda (ov)
                               (list (overlay-start ov)
                                     (overlay-end ov)
                                     (overlay-get ov 'invisible)))
                             (overlays-in (point-min) (point-max))))))
          (benedict-chat-fold--isearch-open)
          (state "after-open")
          (let ((isearch-success t)
                (isearch-other-end (marker-position think-start)))
            (benedict-chat-fold--isearch-update))
          (state "after-think-match")
          (should-not (get-char-property (marker-position think-start) 'invisible))
          (should (eq (get-text-property (marker-position tool-start) 'invisible)
                      'benedict-tool-details))
          (let ((isearch-success t)
                (isearch-other-end (marker-position tool-start)))
            (benedict-chat-fold--isearch-update))
          (state "after-tool-match")
          (should (eq (get-char-property (marker-position think-start) 'invisible)
                      'benedict-chat-thinking))
          (should-not (get-text-property (marker-position tool-start) 'invisible))
          (benedict-chat-fold--isearch-close)
          (state "after-close")
          (should (eq (get-char-property (marker-position think-start) 'invisible)
                      'benedict-chat-thinking))
          (should (eq (get-text-property (marker-position tool-start) 'invisible)
                      'benedict-tool-details)))))))

(ert-deftest benedict-chat-fold-tool-toggle-repairs-invisibility-spec ()
  (benedict-chat-fold-test--with-chat-buffer
    (let* ((item (list :metadata (list :status 'success)
                       :tool-call (list :name 'repair-spec)
                       :content "Body"
                       :tool-folded t))
           (alias (benedict-fold-core-spec-alias benedict-chat-fold-tool-spec)))
      (benedict-chat--render-tool-item (current-buffer) item)
      (goto-char (plist-get item :header-start))
      (benedict-chat-tool-toggle)
      (let ((inhibit-read-only t))
        (setq buffer-invisibility-spec nil))
      (goto-char (plist-get item :header-start))
      (benedict-chat-tool-toggle)
      (let ((start (marker-position (plist-get item :content-start)))
            (end (marker-position (plist-get item :content-end))))
        (should (and start end))
        (should (memq alias buffer-invisibility-spec))
        (should (null (text-property-not-all start end 'invisible alias)))
        (should (invisible-p start))))))

(ert-deftest benedict-chat-fold-tool-toggle-real-chat-buffer ()
  (benedict-chat-fold-test--with-chat-buffer
    (let* ((item (list :metadata (list :status 'success)
                       :tool-call (list :name 'real-chat)
                       :content "Body"
                       :tool-folded t))
           (alias (benedict-fold-core-spec-alias benedict-chat-fold-tool-spec)))
      (benedict-chat--render-tool-item (current-buffer) item)
      (let* ((header (plist-get item :header-start))
             (body-start (marker-position (plist-get item :content-start)))
             (body-end (marker-position (plist-get item :content-end))))
        (should (eq (get-text-property header 'benedict-region-kind) 'header))
        (should-not (get-text-property header 'invisible))
        (should (eq (get-text-property body-start 'invisible) alias))
        (goto-char header)
        (benedict-chat-tool-toggle)
        (should-not (get-text-property body-start 'invisible))
        (should (null (text-property-any body-start body-end 'invisible alias)))
        (should-not (get-text-property header 'invisible))
        (goto-char header)
        (benedict-chat-tool-toggle)
        (should (memq alias buffer-invisibility-spec))
        (should (eq (get-text-property body-start 'invisible) alias))
        (should-not (get-text-property header 'invisible))))))

(ert-deftest benedict-chat-fold-tool-header-rewrite-keeps-body-range ()
  (benedict-chat-fold-test--with-chat-buffer
    (let ((item (list :metadata (list :status 'success)
                      :tool-call (list :name 'marker-guard)
                      :content "Range"
                      :tool-folded t)))
      (benedict-chat--render-tool-item (current-buffer) item)
      (let* ((header (plist-get item :header-start))
             (h-pos (marker-position header))
             (body-start (plist-get item :content-start))
             (body-end (plist-get item :content-end))
             (body-start-pos (marker-position body-start))
             (body-end-pos (marker-position body-end)))
        (goto-char header)
        (benedict-chat-tool-toggle)
        (goto-char header)
        (benedict-chat-tool-toggle)
        (should (= (marker-position (plist-get item :header-start)) h-pos))
        (should (= (marker-position body-start) body-start-pos))
        (should (= (marker-position body-end) body-end-pos))
        (should (< (marker-position (plist-get item :header-start))
                   (marker-position body-start)))
        (should (< (marker-position body-start)
                   (marker-position body-end)))))))

(ert-deftest benedict-chat-fold-tool-repair-invisibility-real-buffer ()
  (benedict-chat-fold-test--with-chat-buffer
    (let* ((item (list :metadata (list :status 'success)
                       :tool-call (list :name 'repair-real)
                       :content "Body"
                       :tool-folded t))
           (alias (benedict-fold-core-spec-alias benedict-chat-fold-tool-spec)))
      (benedict-chat--render-tool-item (current-buffer) item)
      (goto-char (plist-get item :header-start))
      (benedict-chat-tool-toggle)
      (goto-char (plist-get item :header-start))
      (benedict-chat-tool-toggle)
      (let ((inhibit-read-only t))
        (setq buffer-invisibility-spec nil))
      (benedict-fold-core-repair-invisibility)
      (let ((start (marker-position (plist-get item :content-start)))
            (end (marker-position (plist-get item :content-end))))
        (should (memq alias buffer-invisibility-spec))
        (should (invisible-p start))
        (should (null (text-property-not-all start end 'invisible alias)))))))

(ert-deftest benedict-chat-fold-isearch-restores-chat-visibility ()
  (benedict-chat-fold-test--with-chat-buffer
    (let* ((thinking (list :content-start (point-marker)))
           (alias-thinking (benedict-fold-core-spec-alias benedict-chat-fold-thinking-spec))
           (alias-tool (benedict-fold-core-spec-alias benedict-chat-fold-tool-spec)))
      (let ((inhibit-read-only t))
        (insert "thinking")
        (plist-put thinking :content-end (copy-marker (point) t))
        (insert "\n"))
      (plist-put thinking :thinking-folded t)
      (benedict-chat-fold-set-thinking-folded thinking t)
      (let* ((tool (list :metadata (list :status 'success)
                         :tool-call (list :name 'isearch)
                         :content "tool-body"
                         :tool-folded t)))
        (benedict-chat--render-tool-item (current-buffer) tool)
        (let* ((thinking-pos (marker-position (plist-get thinking :content-start)))
               (tool-pos (marker-position (plist-get tool :content-start))))
          (benedict-chat-fold--isearch-open)
          (let ((isearch-success t)
                (isearch-other-end thinking-pos))
            (benedict-chat-fold--isearch-update))
          (should-not (get-char-property thinking-pos 'invisible))
          (should (eq (get-text-property tool-pos 'invisible) alias-tool))
          (let ((isearch-success t)
                (isearch-other-end tool-pos))
            (benedict-chat-fold--isearch-update))
          (should (invisible-p thinking-pos))
          (should (cl-some (lambda (ov)
                             (eq (overlay-get ov 'invisible) alias-thinking))
                           (overlays-at thinking-pos)))
          (should-not (get-text-property tool-pos 'invisible))
          (benedict-chat-fold--isearch-close)
          (benedict-fold-core-repair-invisibility)
          (benedict-chat-fold-set-thinking-folded thinking t)
          (should (invisible-p thinking-pos))
          (should (cl-some (lambda (ov)
                             (eq (overlay-get ov 'invisible) alias-thinking))
                           (overlays-at thinking-pos)))
          (should (eq (get-text-property tool-pos 'invisible) alias-tool)))))))

(provide 'test/benedict-chat-fold-test)
;;; test/benedict-chat-fold-test.el ends here
