;;; benedict-provider-gemini-test.el --- Tests for Gemini provider -*- lexical-binding: t; -*-

(require 'ert)
(require 'ert-async)
(require 'propcheck)

(let* ((root (file-name-directory (or load-file-name buffer-file-name)))
       (repo (expand-file-name ".." root)))
  (add-to-list 'load-path repo))

(require 'benedict-provider-gemini)

(defun benedict-provider-gemini-test--json-get (alist key)
  "Return KEY from JSON-like ALIST using string comparison."
  (alist-get key alist nil nil #'string=))

(propcheck-deftest benedict-provider-gemini-pkce-flow-prop ()
  "PKCE flow (verifier -> challenge) works for any 32 random bytes."
  (let ((bytes (cl-loop repeat 32 collect (propcheck-generate-integer "byte" :min 0 :max 255))))
    (let* ((verifier (benedict-provider-gemini--make-verifier bytes))
           (challenge (benedict-provider-gemini--derive-challenge verifier)))
      (propcheck-should (string-match-p "\\`[-_A-Za-z0-9]+\\'" verifier))
      (propcheck-should (string-match-p "\\`[-_A-Za-z0-9]+\\'" challenge))
      (propcheck-should (not (multibyte-string-p verifier)))
      (propcheck-should (not (multibyte-string-p challenge))))))

(ert-deftest benedict-provider-gemini-generate-verifier-uses-make-verifier ()
  "Verifier generation calls the deterministic helper."
  (cl-letf (((symbol-function 'benedict-provider-gemini--make-verifier)
             (lambda (bytes) (format "mock-%d" (length bytes)))))
    (should (equal (benedict-provider-gemini--generate-verifier) "mock-32"))))

(ert-deftest benedict-provider-gemini-derive-challenge-base64url ()
  "PKCE challenge derivation wraps SHA256 with base64url encoding."
  (let* ((verifier "plain-verifier")
         (expected (base64url-encode-string (secure-hash 'sha256 verifier nil nil t) t)))
    (should (equal (benedict-provider-gemini--derive-challenge verifier) expected))))

(ert-deftest benedict-provider-gemini-state-roundtrip ()
  "State payload encoding round-trips through base64url helpers."
  (let* ((payload (list :verifier "abc" :nonce "xyz"))
         (encoded (benedict-provider-gemini--encode-state payload))
         (decoded (benedict-provider-gemini--decode-state encoded)))
    (should decoded)
    (should (equal (plist-get decoded :verifier) "abc"))
    (should (equal (plist-get decoded :nonce) "xyz"))))

(ert-deftest benedict-provider-gemini-pkce-session-roundtrip ()
  "PKCE state survives auth URL construction and callback parsing."
  (let* ((verifier "test-verifier")
         (state (benedict-provider-gemini--encode-state (list :verifier verifier :nonce "n1")))
         (challenge (benedict-provider-gemini--derive-challenge verifier))
         (auth-url (benedict-provider-gemini--authorization-url challenge state))
         (query (cadr (split-string auth-url "?" t)))
         (params (url-parse-query-string query)))
    (should (equal (cadr (assoc-string "code_challenge" params t)) challenge))
    (should (equal (cadr (assoc-string "code_challenge_method" params t)) "S256"))
    (should (equal (cadr (assoc-string "state" params t)) state))
    (should (equal (cadr (assoc-string "redirect_uri" params t)) benedict-provider-gemini-redirect-uri))
    (let* ((callback (format "%s?code=auth-code&state=%s" benedict-provider-gemini-redirect-uri state))
           (parsed (benedict-provider-gemini--parse-callback callback))
           (decoded (benedict-provider-gemini--decode-state (plist-get parsed :state))))
      (should (equal (plist-get parsed :code) "auth-code"))
      (should decoded)
      (should (equal (plist-get decoded :verifier) verifier))
      (should (equal (plist-get decoded :nonce) "n1")))))

(ert-deftest benedict-provider-gemini-resolve-uses-cache ()
  "Cached credentials skip refresh calls."
  (let ((benedict-provider-gemini--token-cache (make-hash-table :test 'equal)))
    (puthash "refresh-1"
             (list :access "cached-access" :expires (+ (float-time) 999))
             benedict-provider-gemini--token-cache)
    (cl-letf (((symbol-function 'benedict-provider-gemini--auth-source-entry)
               (lambda () (list :secret "refresh-1")))
              ((symbol-function 'benedict-provider-gemini--refresh-access-token)
               (lambda (&rest _)
                 (error "refresh should not be called"))))
      (let ((credential (benedict-provider-gemini--resolve-credential)))
        (should (equal (plist-get credential :access) "cached-access"))
        (should (equal (plist-get credential :refresh) "refresh-1"))))))

(ert-deftest benedict-provider-gemini-resolve-refreshes-when-expired ()
  "Expired cache entries trigger token refresh." 
  (let ((benedict-provider-gemini--token-cache (make-hash-table :test 'equal))
        (refresh-count 0))
    (puthash "refresh-old" (list :access "stale" :expires (float-time))
             benedict-provider-gemini--token-cache)
    (cl-letf (((symbol-function 'benedict-provider-gemini--auth-source-entry)
               (lambda () (list :secret "refresh-old")))
              ((symbol-function 'benedict-provider-gemini--refresh-access-token)
               (lambda (_refresh _entry)
                 (setq refresh-count (1+ refresh-count))
                 (list :access "new-access" :expires (+ (float-time) 3600)
                       :refresh "refresh-old"))))
      (let ((credential (benedict-provider-gemini--resolve-credential)))
        (should (= refresh-count 1))
        (should (equal (plist-get credential :access) "new-access"))
        (should (equal (plist-get credential :refresh) "refresh-old"))))))

(ert-deftest benedict-provider-gemini-refresh-rotates-token ()
  "Refresh flow updates auth-source when Google rotates tokens."
  (let ((updated nil))
    (cl-letf (((symbol-function 'benedict-provider-gemini--token-request)
               (lambda (_payload)
                 (list :status 200
                       :body "{\"access_token\":\"ya29-token\",\"refresh_token\":\"1//new\",\"expires_in\":3600}")))
              ((symbol-function 'benedict-provider-gemini--update-auth-entry)
               (lambda (_entry refresh)
                 (setq updated refresh))))
      (let* ((entry (list :secret "1//old"))
             (result (benedict-provider-gemini--refresh-access-token "1//old" entry)))
        (should (equal updated "1//new"))
        (should (equal (plist-get result :refresh) "1//new"))
        (should (equal (plist-get result :access) "ya29-token"))
        (should (> (plist-get result :expires) (float-time)))))))

(ert-deftest benedict-provider-gemini-refresh-invalid-grant ()
  "Refresh failures bubble useful invalid_grant errors."
  (cl-letf (((symbol-function 'benedict-provider-gemini--token-request)
             (lambda (_payload)
               (list :status 400 :body "{\"error\":\"invalid_grant\"}"))))
    (should-error (benedict-provider-gemini--refresh-access-token "bad" nil)
                  :type 'error)))

(ert-deftest benedict-provider-gemini-payload-shape ()
  "Payload encoding follows Gemini content schema."
  (let* ((request (list :model "gemini-test"
                        :messages (list (list :role 'system :content "system prompt")
                                        (list :role 'user :content "hi")
                                        (list :role 'assistant :content "hello"))
                        :temperature 0.3
                        :max-tokens 256))
         (encoded (benedict-provider-gemini--encode-payload request))
         (decoded (json-parse-string encoded :object-type 'alist :array-type 'list)))
    (should (equal (benedict-provider-gemini-test--json-get decoded "model") "gemini-test"))
    (let ((system (benedict-provider-gemini-test--json-get decoded "systemInstruction")))
      (should system)
      (should (equal (benedict-provider-gemini-test--json-get system "role") "system")))
    (let ((contents (benedict-provider-gemini-test--json-get decoded "contents")))
      (should (= (length contents) 2))
      (should (equal (benedict-provider-gemini-test--json-get (car contents) "role") "user"))
      (should (equal (benedict-provider-gemini-test--json-get (cadr contents) "role") "model")))
    (let* ((config (benedict-provider-gemini-test--json-get decoded "generationConfig"))
           (temperature (benedict-provider-gemini-test--json-get config "temperature"))
           (max-output (benedict-provider-gemini-test--json-get config "maxOutputTokens")))
      (should (= temperature 0.3))
      (should (= max-output 256)))))

(ert-deftest benedict-provider-gemini-header-redaction ()
  "Header redaction masks bearer tokens."
  (let* ((headers (benedict-provider-gemini--build-headers "secret-token"))
         (redacted (benedict-provider-gemini--redact-headers headers))
         (auth-original (cdr (assoc "Authorization" headers)))
         (auth-redacted (cdr (assoc "Authorization" redacted))))
    (should (string-match-p "Bearer" auth-redacted))
    (should (not (equal auth-original auth-redacted)))))

(ert-deftest-async benedict-provider-gemini-login-persists-refresh-token (done)
  "Simulated OAuth login persists refresh token and seeds cache."
  (let* ((verifier "unit-test-verifier")
         (access-token "ya29.unit-access")
         (refresh-token "1//unit-refresh")
         (state-value nil)
         (opened-url nil)
         (copied-url nil)
         (read-prompt nil)
         (auth-write nil)
         (token-request-count 0)
         (orig-encode (symbol-function 'benedict-provider-gemini--encode-state)))
    (let ((benedict-provider-gemini--token-cache (make-hash-table :test 'equal))
          (benedict-provider-gemini-auth-source-host "gemini-integration")
          (benedict-provider-gemini-auth-source-user "oauth-integration"))
      (cl-letf* (((symbol-function 'benedict-provider-gemini--generate-verifier)
                  (lambda () verifier))
                 ((symbol-function 'benedict-provider-gemini--encode-state)
                  (lambda (plist)
                    (setq state-value (funcall orig-encode plist))
                    state-value))
                 ((symbol-function 'benedict-provider-gemini--auth-source-entry)
                  (lambda () nil))
                 ((symbol-function 'auth-source-add)
                  (lambda (&rest plist)
                    (setq auth-write plist)
                    plist))
                 ((symbol-function 'browse-url)
                  (lambda (url)
                    (setq opened-url url)))
                 ((symbol-function 'kill-new)
                  (lambda (value)
                    (setq copied-url value)))
                 ((symbol-function 'read-string)
                  (lambda (prompt)
                    (setq read-prompt prompt)
                    (should state-value)
                    (format "%s?code=test-code&state=%s"
                            benedict-provider-gemini-redirect-uri state-value)))
                 ((symbol-function 'benedict-provider-gemini--token-request)
                  (lambda (_payload)
                    (setq token-request-count (1+ token-request-count))
                    (list :status 200
                          :body (json-encode
                                 `(("access_token" . ,access-token)
                                   ("refresh_token" . ,refresh-token)
                                   ("expires_in" . 120)))))))
        (condition-case err
            (progn
              (benedict-provider-gemini-login)
              (should (equal read-prompt "Paste Gemini redirect URL: "))
              (should opened-url)
              (should (equal opened-url copied-url))
              (should (string-match-p (regexp-quote state-value) opened-url))
              (should (= token-request-count 1))
              (should auth-write)
              (should (equal (plist-get auth-write :secret) refresh-token))
              (should (equal (plist-get auth-write :host) benedict-provider-gemini-auth-source-host))
              (should (equal (plist-get auth-write :user) benedict-provider-gemini-auth-source-user))
              (let ((cached (gethash refresh-token benedict-provider-gemini--token-cache)))
                (should cached)
                (should (equal (plist-get cached :access) access-token))
                (should (> (plist-get cached :expires) (float-time))))
              (funcall done))
          (error (funcall done err)))))))

(provide 'benedict-provider-gemini-test)
;;; benedict-provider-gemini-test.el ends here
